## return()
- 이터레이터를 종료시킴

---

### 1. return()

```js
function * sports(count) {
  while(true) {
    yield ++count;
  };
};
const obj = sports(10);
console.log(obj.next());
console.log(obj.return(70)); // 이터레이터를 종료시키며 파라미터 값 70을 반환
console.log(obj.next(50));
```

```
//실행결과
{value: 11, done: false}
{value: 70, done: true}
{value: undefined, done: false}
```

---

## throw()
- Error를 의도적으로 발생
- 제너레이터 함수의 catch()문에서 에러를 받음
- 에러 발생해도 제너레이터가 종료되지 않음
- 하지만 제너레이터 함수 안에서 에러가 발생하면 이터레이터가 종료

---

### 1. throw()

```js
function * sports(count) {
  try {
    yield 10;
  } catch(message) {
    yield message;
  };
  yield 20;
};
const obj = sports(10);
console.log(obj.next());
console.log(obj.throw('에러 발생'));
console.log(obj.next());
```

```
//실행결과
{value: 10, done: false}
{value: 에러 발생, done: false}
{value: 20, done: false}
```

### 2. 제너레이터 안에 throw

```js
function * sports(count) {
  throw '에러 발생';
  yield 10;
};
const obj = sports(10);
try {
  const result = obj.next();
} catch(msg) {
  console.log(msg);
}
console.log(obj.next());
```

```
//실행결과
에러 발생
{value: undefined, done: true}
```